### ISSUE TITLE
Abstracting different app entities

### ISSUE THREAD

**Issue by ayamba-coder** [FotieMConstant/LAN-Tube#3]
Currently, the codebase has a structure in which data and layout are all mixed. This becomes a little hassle for new devs and inflexible for maintainibility.
Proposal: To implement and abstract each unit into its separate entity using any PHP framework(e.g CI i prefer).

**Comment by FotieMConstant** [comment]
Hi, @ayamba-coder. Thanks for opening this issue. However, currently we are working on a completely new codebase of Lantube, with react and back-end separated from Front-End. This repository is no longer maintained. Please kindly visit the new repository at : [lantube-v2](https://github.com/TatchumNono/lantube-v2)

**Comment by ayamba-coder** [comment]
okay can't wait to jump into it

**Comment by FotieMConstant** [comment]
Awesome, we can't wait to have you in either.
